default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
files: '^src/.*\.pyi?$|^test/.*\.pyi?$'
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev:v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0' # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies: [Flake8-pyproject]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
    -   id: black
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)