[tool.poetry]   
name = "Leuphana-IPE"
version = "0.1.0"
description = ""
authors = ["Nele-Pauline Suffo  <nele.suffo@leuphana.dem>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
filelock = "*"
numpy = "*"
packaging = ">=20.0"
requests = "*"
safetensors = ">=0.4.1"
tokenizers = ">=0.14,<0.19"
matplotlib = ">=3.3.0"
opencv-python = "*"
pandas = ">=1.1.4"
pillow = ">=7.1.2"
psutil = "*"
pyyaml = ">=5.3.1"
scipy = ">=1.4.1"
seaborn = ">=0.11.0"
thop = ">=0.1.1"
torch = ">=1.8.0"
torchvision = ">=0.9.0"
tqdm = ">=4.64.0"
tensorflow = "*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"    