---
title: "quantex_results"
author: "Nele-Pauline Suffo"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(lme4)
library(brms)
library(lmerTest)
library(ggplot2)
library(ggthemes)
library(tidybayes)
library(forcats)
library(stringr)
library(tidyr)
```

```{r load-data}
utterance_01_df <- read_csv("../paper/data/utterance_01_df.csv", show_col_types = FALSE)
utterance_02_df <- read_csv("../paper/data/utterance_02_df.csv", show_col_types = FALSE)
person_presence_03_df <- read_csv("../paper/data/person_presence_03_df.csv", show_col_types = FALSE)
interactions_04_df <- read_csv("../paper/data/interactions_04_df.csv", show_col_types = FALSE)
toys_05_df <- read_csv("../paper/data/toys_05_df.csv", show_col_types = FALSE)
```

# Model 1a
## Run Model 1a
```{r}
# new data file for modelling
utterance_01a_df <- utterance_01_df %>%
  mutate(play_context = factor(play_context, levels = c("alone", "social")),
         child_id = factor(child_id),
         z_age = scale(age))

# bayesian model - no convergence problems and more options for visuals

model_01a <- brm(kchi_present ~ z_age * play_context + ( play_context | child_id),
               data = utterance_01a_df,
               family = bernoulli(),
               chains = 4, 
               cores = 4,
               iter = 2000,
               #threads = threading(8), # to speed things up wehn on a cluster
               #backend = "cmdstanr", # to speed things up wehn on a cluster
               #control = list(adapt_delta = 0.95, max_treedepth = 20) # control option in case of nonconvergence of chains
    )%>%add_criterion("loo") # add loo for model comparison

model_01a
```
## Visuals 1a

```{r}
ndata1a <- m_utterance_01a_df%>%
  distinct(z_age, age, play_context) # generate new data set for which we want to generate predictions based on the model, this does not include child because we want the "average" or "marginal" predicitons, that is, average developmental trajectory for each play context. We need age in there for plotting


post1a <- fitted(model_01a, newdata = ndata1a, re_formula = NA)%>%
  as_tibble() %>%
  bind_cols(ndata1a)

ggplot()+
  geom_smooth(data = post1a, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =play_context, col = play_context), stat = "identity", alpha = .25)+ # plot the predicted trajectories
  theme_bw()+
  scale_color_ptol(name = "Play context")+
  scale_fill_ptol(name = "Play context")+
  ylim(0,1)+
  labs(x = "Age in years", y="Probability of key child utterance being present")+
  theme(
    #legend.position = c(0.8, 0.15), 
    legend.background = element_rect(colour = "black", size = 0.5, linetype = "solid"))
```
 # Model 1b
 ## Run Model 1b
```{r}
# new data file for modelling
utterance_01b_df <- utterance_01_df%>%
    filter(play_context == "alone")%>%
    filter(!object_class %in% c("food", "kitchenware"))%>%
    mutate(child_id = factor(child_id),
           gaze = factor(gaze_direction, levels = c("none", "1.0", "0.0"), labels = c("na", "yes", "no")),
           z_age = scale(age),
        )
# bayesian model - no convergence problems and more options for visuals

model_01b <- brm(kchi_present ~ z_age * object_class + (1 | child_id),
               data = utterance_01b_df,
               family = bernoulli(),
               chains = 4, 
               cores = 4,
               iter = 4000,
               #threads = threading(8), # to speed things up wehn on a cluster
               #backend = "cmdstanr", # to speed things up wehn on a cluster
               control = list(adapt_delta = 0.95, max_treedepth = 20) # control option in case of nonconvergence of chains
    )%>%add_criterion("loo") # add loo for model comparison

model_01b
```
## Visuals 1b
```{r}
ndata1b <- utterance_01b_df%>%
  distinct(z_age, age, object_class) # generate new data set for which we want to generate predictions based on the model, this does not include child because we want the "average" or "marginal" predicitons, that is, average developmental trajectory for each play context. We need age in there for plotting


post1b <- fitted(model_01b, newdata = ndata1b, re_formula = NA)%>%
  as_tibble() %>%
  bind_cols(ndata1b)

ggplot()+
  geom_smooth(data = post1b, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =object_class, col = object_class), stat = "identity", alpha = .25)+ # plot the predicted trajectories
  theme_bw()+
  scale_color_ptol(name = "Play context")+
  scale_fill_ptol(name = "Play context")+
  ylim(0,1)+
  labs(x = "Age in years", y="Probability of key child utterance being present")+
  theme(
    #legend.position = c(0.8, 0.15), 
    legend.background = element_rect(colour = "black", size = 0.5, linetype = "solid"))
```

# Model 1c
## Run model 1c
```{r}
utterance_01c_df <- utterance_01_df%>%
    filter(play_context == "social")%>%
    mutate(child_id = factor(child_id),
           gaze = factor(gaze_direction, levels = c("none", "1.0", "0.0"), labels = c("na", "yes", "no")),
           person_age_class = factor(person_age_class, levels = c("none", "adult", "child", "both")),
           z_age = scale(age),
           #z_proximity = scale(proximity),
           #face_present = factor(face_present, levels = c("none", "1.0", "0.0"), labels = c("na", "yes", "no")),
        )
#model_01c <- brm(kchi_present ~ z_age * person_age_class *gaze * proximity * face_present + (1 | child_id)

model_01c <- brm(kchi_present ~ z_age * person_age_class + (1 | child_id), # remove random slopes within child just because it takes long to run them, bring them back later; also need to remove some variables becasue too little data
               data = utterance_01c_df,
               family = bernoulli(),
               chains = 4, 
               cores = 4,
               iter = 5000,
               #threads = threading(8), # to speed things up wehn on a cluster
               #backend = "cmdstanr", # to speed things up wehn on a cluster
               control = list(adapt_delta = 0.95, max_treedepth = 20) # control option in case of nonconvergence of chains
    )%>%add_criterion("loo") # add loo for model comparison


model_01c
```

## Visuals 1c
```{r}
ndata1c <- utterance_01c_df%>%
  distinct(z_age, age, person_age_class) # generate new data set for which we want to generate predictions based on the model, this does not include child because we want the "average" or "marginal" predicitons, that is, average developmental trajectory for each play context. We need age in there for plotting

post1c <- fitted(model_01c, newdata = ndata1c, re_formula = NA)%>%
  as_tibble() %>%
  bind_cols(ndata1c)

ggplot()+
  geom_smooth(data = post1c, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =person_age_class, col = person_age_class), stat = "identity", alpha = .25)+ # plot the predicted trajectories
  theme_bw()+
  scale_color_ptol(name = "Person age")+
  scale_fill_ptol(name = "Person age")+
  ylim(0,1)+
  facet_grid(~ person_age_class) # use when there are more variables 
  labs(x = "Age in years", y="Probability of key child utterance being present")+
  theme(
    #legend.position = c(0.8, 0.15), 
    legend.background = element_rect(colour = "black", size = 0.5, linetype = "solid"))
```

# Model 2
## Run model 2
```{r}
utterance_02_df <- utterance_02_df%>%
    mutate(child_id = factor(child_id),
           gaze = factor(gaze_direction, levels = c("none", "1.0", "0.0"), labels = c("na", "yes", "no")),
           person_age_class = factor(person_age_class, levels = c("none", "adult", "child", "both")),
           z_age = scale(age),
           #face_present = factor(face_present, levels = c("none", "1.0", "0.0"), labels = c("na", "yes", "no")),
           #z_proximity = scale(proximity)
        )

model_02 <- brm(cds_present ~ z_age * person_age_class  * gaze  + (1 | child_id), # remove random slopes within child just because it takes long to run them, bring them back later; also need to remove some variables becasue too little data
               data = utterance_02_df,
               family = bernoulli(),
               chains = 4, 
               cores = 4,
               iter = 5000,
               #threads = threading(8), # to speed things up wehn on a cluster
               #backend = "cmdstanr", # to speed things up wehn on a cluster
               control = list(adapt_delta = 0.95, max_treedepth = 20) # control option in case of nonconvergence of chains
    )%>%add_criterion("loo") # add loo for model comparison

model_02
```

## Visuals 2
```{r}
ndata2 <- utterance_02_df%>%
  distinct(z_age, age, person_age_class, gaze) # generate new data set for which we want to generate predictions based on the model, this does not include child because we want the "average" or "marginal" predicitons, that is, average developmental trajectory for each play context. We need age in there for plotting

post2 <- fitted(model_02, newdata = ndata2, re_formula = NA)%>%
  as_tibble() %>%
  bind_cols(ndata2)

ggplot()+
  geom_smooth(data = post2, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =person_age_class, col = person_age_class), stat = "identity", alpha = .25)+ # plot the predicted trajectories
  theme_bw()+
  scale_color_ptol(name = "Person Age")+
  scale_fill_ptol(name = "Person Age")+
  ylim(0,1)+
  facet_grid(~ person_age_class) # use when there are more variables 
  labs(x = "Age in years", y="Probability of key child utterance being present")+
  theme(
    #legend.position = c(0.8, 0.15), 
    legend.background = element_rect(colour = "black", size = 0.5, linetype = "solid"))
```

# Model 3
## Run model 3
```{r}
person_presence_03_df <- person_presence_03_df%>%
    mutate(child_id = factor(child_id),
           z_age = scale(age),
        )

model_03 <- brm(person_age_class ~ z_age + (1 | child_id), # remove random slopes within child just because it takes long to run them, bring them back later; also need to remove some variables becasue too little data
               data = person_presence_03_df,
               family = categorical(),
               chains = 4, 
               cores = 4,
               iter = 5000,
               #threads = threading(8), # to speed things up wehn on a cluster
               #backend = "cmdstanr", # to speed things up wehn on a cluster
               control = list(adapt_delta = 0.95, max_treedepth = 20) # control option in case of nonconvergence of chains
    )%>%add_criterion("loo") # add loo for model comparison

model_03
```

## Visuals 3
```{r}
ndata3 <- person_presence_03_df%>%
  distinct(z_age, age) # generate new data set for which we want to generate predictions based on the model, this does not include child because we want the "average" or "marginal" predicitons, that is, average developmental trajectory for each play context. We need age in there for plotting

post3 <- fitted(model_03, newdata = ndata3, re_formula = NA)%>%
  as_tibble() %>%
  bind_cols(ndata3)
post3_long <- post3 %>%
  select(starts_with("Estimate"), z_age, age) %>%
  pivot_longer(
    cols = starts_with("Estimate"),
    names_to = "person_age_class",
    values_to = "estimate"
  ) %>%
  mutate(
    person_age_class = str_remove_all(person_age_class, "Estimate.P\\(Y = |\\)")
  )

# Step 3: Plot as flag (stacked area) plot
ggplot(post3_long, aes(x = age, y = estimate, fill = person_age_class)) +
  geom_area(color = "black", size = 0.3) +
  scale_fill_brewer(palette = "Set2", name = "Person Age Class") +
  labs(
    title = "Predicted Probability of Person Age Class Over Time",
    x = "Age (in years)",
    y = "Predicted Probability"
  ) +
  theme_bw()
```

# Model 4
## Run model 4
```{r}
interactions_04_df <- interactions_04_df%>%
    mutate(child_id = factor(child_id),
           z_age = scale(age),
        )

model_04 <- brm(interaction_type ~ z_age + (1 | child_id), # remove random slopes within child just because it takes long to run them, bring them back later; also need to remove some variables becasue too little data
               data = interactions_04_df,
               family = categorical(),
               chains = 4, 
               cores = 4,
               iter = 2000,
               #threads = threading(8), # to speed things up wehn on a cluster
               #backend = "cmdstanr", # to speed things up wehn on a cluster
               #control = list(adapt_delta = 0.95, max_treedepth = 20) # control option in case of nonconvergence of chains
    )%>%add_criterion("loo") # add loo for model comparison

model_04
```

## Visuals 4
```{r}
ndata4 <- interactions_04_df%>%
  distinct(z_age, age) # generate new data set for which we want to generate predictions based on the model, this does not include child because we want the "average" or "marginal" predicitons, that is, average developmental trajectory for each play context. We need age in there for plotting

post4 <- fitted(model_04, newdata = ndata4, re_formula = NA)%>%
  as_tibble() %>%
  bind_cols(ndata4)
post4_long <- post4 %>%
  select(starts_with("Estimate"), z_age, age) %>%
  pivot_longer(
    cols = starts_with("Estimate"),
    names_to = "interaction_type",
    values_to = "estimate"
  ) %>%
  mutate(
    interaction_type = str_remove_all(interaction_type, "Estimate.P\\(Y = |\\)")
  )

# Step 3: Plot as flag (stacked area) plot
ggplot(post4_long, aes(x = age, y = estimate, fill = interaction_type)) +
  geom_area(color = "black", size = 0.3) +
  scale_fill_brewer(palette = "Set2", name = "Interaction Type") +
  labs(
    title = "Predicted Probability of Interaction Types Over Time",
    x = "Age (in years)",
    y = "Predicted Probability"
  ) +
  theme_bw()
```

# Model 5
## Run model 5
```{r}
toys_05_df <- toys_05_df%>%
    mutate(child_id = factor(child_id),
           z_age = scale(age),
           toy_present = factor(toy_present, levels = c("none", "1.0", "0.0"), labels = c("na", "yes", "no")),
        )

model_05 <- brm(toy_present ~ z_age * toy_class * social_context + (toy_class * social_context | child_id), 
               data = toys_05_df,
               family = bernoulli(),
               chains = 4, 
               cores = 4,
               iter = 2000,
               #threads = threading(8), # to speed things up wehn on a cluster
               #backend = "cmdstanr", # to speed things up wehn on a cluster
               #control = list(adapt_delta = 0.95, max_treedepth = 20) # control option in case of nonconvergence of chains
    )%>%add_criterion("loo") # add loo for model comparison

model_05
```

## Visuals 5
```{r}
ndata5 <-toys_05_df%>%
  distinct(z_age, age, toy_class, social_context)


post5 <- fitted(model_05, newdata = ndata5, re_formula = NA)%>%
  as_tibble() %>%
  bind_cols(ndata1a)

ggplot()+
  geom_smooth(data = post5, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =play_context, col = play_context), stat = "identity", alpha = .25)+ # plot the predicted trajectories
  theme_bw()+
  scale_color_ptol(name = "Play context")+
  scale_fill_ptol(name = "Play context")+
  ylim(0,1)+
  labs(x = "Age in years", y="Probability of key child utterance being present")+
  theme(
    #legend.position = c(0.8, 0.15), 
    legend.background = element_rect(colour = "black", size = 0.5, linetype = "solid"))
```